auto: true  

markdown: rdiscount  
pygments: true  
paginate: 8  
permalink: /:title  

title: Hihera  
url: http://hihera.github.io  
feed: /atom.xml    
author_info: <a href="http://hihera.github.io/">hihera</a>  